### ISSUE TITLE
"make qemu" error

### ISSUE THREAD

**Issue by kehao95** [THSS13/XV6#7]
![Error log 0](https://cloud.githubusercontent.com/assets/6213976/11211742/75f9d660-8d6c-11e5-9ce7-3b8fd9a2e3f3.png)

![image](https://cloud.githubusercontent.com/assets/6213976/11211770/c32d2f86-8d6c-11e5-9964-c23cd5eb31a5.png)

Finally got "No bootable device" error

**Comment by kehao95** [comment]
尝试了换Ubuntu版本，使用VitrualBox安装了 ubuntu-12.04.5-desktop-i386 依旧不能运行……

**Comment by TLawrenceCHEN** [comment]
从github clone到本地后，需要在根目录下执行"chmod -R 777 xv6"命令，之后进到xv6文件夹里，最好先"make clean"，再"make"，"make qemu"就可以执行了。网络学堂上的版本同上。

**Comment by CooperKuo** [comment]
thanks a lot!!

**Comment by cooperkuo** [comment]
thanks a lot!!
